name: "Build and test"

on:
  pull_request:

jobs:
  build:
    name: Build and Test ghe-visualizer
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://goproxy.githubapp.com/mod,https://proxy.golang.org/,direct
      GOPRIVATE: ''
      GONOPROXY: ''
      GONOSUMDB: github.com/github/*
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # From https://github.com/github/goproxy/blob/main/doc/user.md#set-up:
      - name: Configure Go private module access
        run: |
          echo "machine goproxy.githubapp.com login nobody password ${{ secrets.GOPROXY_TOKEN }}" >> $HOME/.netrc

      - uses: actions/setup-go@v4.1.0
        with:
          go-version-file: 'go.mod'

#      - name: Build packages
#        run: make build

      - name: Run tests
        run: make test